### ISSUE TITLE
Multiple background images and dim

### ISSUE THREAD

**Issue by themerchant** [complexlogic/flex-launcher#1]
What a simple and elegant launcher. There are only two things it is missing for my purposes:

1. The ability to periodically switch between background images, like a slideshow. So instead of specifying just one image, I'd like to specify a folder.
2. Screensaver mode when the launcher has been idle for X amount of time.

**Comment by complexlogic** [comment]
>The ability to periodically switch between background images, like a slideshow. So instead of specifying just one image, I'd like to specify a folder.

I have this planned for a future release. I envision it as being similar to Kodi's Artist Slideshow addon. The user specifies a folder that contains background images. The program will rotate the backgrounds randomly and provide a nice fading effect for the transition between the images. The user will be able to specify the background duration, and the transition/fade time between images.

>Screensaver mode when the launcher has been idle for X amount of time.

This is a good idea that I hadn't considered yet. The screen will go dim after it has been idle for a while, and the user could specify the idle time and the amount to dim the screen (e.g. 50%)? Is that what you had in mind?

**Comment by themerchant** [comment]
Yes, exactly what I had in mind, thanks!

**Comment by complexlogic** [comment]
Thanks for the feedback. I will implement both of these features in a future release. Not the next release, but the one after that most likely.

I'll keep this issue open in the meantime.

**Comment by complexlogic** [comment]
Both features are implemented in the latest release, [v1.2](https://github.com/complexlogic/flex-launcher/releases/tag/v1.2). The screensaver is disabled by default, so you will need to enable it in your configuration file. See the latest [configuration file documentation](https://github.com/complexlogic/flex-launcher/blob/master/extra/docs/configuration.md) for details.

If you encounter problems with either feature, please open a new issue.
