### ISSUE TITLE
screensaver help

### ISSUE THREAD

**Issue by jp8311** [complexlogic/flex-launcher#16]
I'm loving this program, its exactly the solution I envisioned when I started searching. Well done!

I have a question about the screensaver - I'm trying to tune my htpc sleep behaviour.
The dim function is lovely and throws a really classy vibe when combined with the slideshow background, but I'm wondering if I can combine this with the windows screensaver and power saving functions.

Currently these are disabled while flex-launcher runs. I'd like to have these remain enabled if possible to prevent oled icon burn in. Unfortunately the TV's power saving features are non existant and I'm looking for a failsafe.

Google is not really bringing up a solution to enable screensaver and sleep functions in a full screen app, only disable them.

Are you aware of a way I can achieve this behaviour?

**Comment by complexlogic** [comment]
SDL [disables the OS screensaver by default](https://wiki.libsdl.org/SDL_HINT_VIDEO_ALLOW_SCREENSAVER), but it would be relatively easy to allow it. I could add another config option.

**Comment by complexlogic** [comment]
I've uploaded a [test build](https://github.com/complexlogic/flex-launcher/files/8895789/flex-launcher-1.7-modified-screensaver-win64.zip) with the hint set to 1 permanently. I checked SDL's source code, and this should allow both the Windows screensaver and sleep to function properly. Please download, give it a test, and let me know if it works for you

**Comment by complexlogic** [comment]
>It seems when flex launcher is open the power saving and screen saver inside launched apps, like jellyfin or steam, do not trigger.

Most likely this is the launched app preventing the screensaver, not Flex Launcher. The Steam client is based on SDL (same as Flex Launcher), so it is likely using the same default setting that was mentioned above. Also, it seems that [many other users](https://github.com/ValveSoftware/steam-for-linux/issues/5532) have reported the same issue with Steam inhibiting the screensaver. In general, this behavior is common for fullscreen applications.

>However flex-launcher is resizing now when it wakes from sleep to 1/4 of the screen, which isn't behaviour I observed before this change.

I am not able to reproduce this. Not sure how to proceed. Any more details that could help with the debugging?

**Comment by complexlogic** [comment]
I've done some testing over the last few days. For me, the sleep function won't activate in Steam Big Picture Mode regardless of whether it was launched standalone or via Flex Launcher. For Jellyfin, it *does* activate for both launch cases. In other words, I am seeing the same behavior in the programs regardless of whether Flex Launcher was used or not.

I am not sure if the inconsistencies you are experiencing are really a bug in Flex Launcher, or if it is something to do with your setup. But I can't imagine why Flex Launcher could be blocking the sleep in the launched program, but not in the launcher itself. I'm planning on merging this feature in an option in a future release unless you can provide any other details that could help me reproduce the issue you are seeing.

**Comment by complexlogic** [comment]
> are you aware of a way to trigger a minimise for all background programs on a programming launch

No, but I wouldn't expect that multiple applications should be running at the same time on an HTPC in a typical use case. Consider changing `OnLaunch` to "None", or you might be able to achieve the minimizing functionality by launching scripts that perform some action in addition to starting your desired application.

I've implemented the allow screensaver functionality as a setting `InhibitOSScreensaver` in the latest release, [v1.8](https://github.com/complexlogic/flex-launcher/releases/tag/v1.8).
