### ISSUE TITLE
Icons for apps like Disney Plus and Netflix not showing

### ISSUE THREAD

**Issue by jenbirb0** [complexlogic/flex-launcher#17]
I started using Flex launcher and edited the config to have netflix and disney plus as the options and have pictures in the .\asset\icons folder for each. Both are png images, but they dont show in the launcher, only the names show. Disney plus icon is "download" and netflix is "downloadd"

Heres the code 

[Main]
Entry1=Disney+;.\assets\icons\download.png;"C:\Users\Imlop\OneDrive\Desktop\Disney+.lnk"
Entry2=Netflix;.assets\icons\downloadd.png;"C:\Users\Imlop\OneDrive\Desktop\Netflix.lnk"
Entry3=System;.\assets\icons\system.png;:submenu System

**Comment by complexlogic** [comment]
If an image failed to load, the launcher will create a log file with the specific error message. Check for a text file `flex-launcher.log` in the same folder as the executable. Please paste the contents of the log.

At a brief glance, though, I can tell that you have a typo for your Netflix entry. It should be `.\assets`, not `.assets`

**Comment by jenbirb0** [comment]
Okay, I fixed the typo. heres the error log 
[flex-launcher.log](https://github.com/complexlogic/flex-launcher/files/9077693/flex-launcher.log)

**Comment by jenbirb0** [comment]
So upon further inspection I found out that I had the icons in the wrong folder, the icons were in the zipped flex launcher file not the extracted one. Sorry for the bother.
