### ISSUE TITLE
OnLaunch=Hide doesn't seem to function well with Browser

### ISSUE THREAD

**Issue by ams3401** [complexlogic/flex-launcher#20]
Hello,

I'm trying to implement a regular internet browser shortcut to this awesome launcher.

Below is the code I have in config.ini
`Entry2=Live Sport;.\assets\icons\sports.png;"C:\Program Files (x86)\Microsoft\Edge\Application\msedge_proxy.exe" --start-fullscreen https://totalsportk.org/nflstreams `

When I launch the browser shortcut in the launcher, the browser pops up underneath the launcher despite `OnLaunch=Hide` in config.ini and I can't see the browser window unless I Alt-tab.

All other implementations seem to work fine, just the internet browser that's causing the issue.
Is this something that can be fixed?

Thank you.

**Comment by complexlogic** [comment]
The browser focusing problem is a known issue on Windows. I implemented a workaround for it, but it only runs for a specific list of process names. I just added `msedge_proxy.exe` to the list. Please try [this modified build](https://github.com/complexlogic/flex-launcher/files/9795111/flex-launcher-1.8-modified-win64.zip) and let me know if it works for you. If so, I'll merge the change for a new formal release.

As a side note: when using Edge with Flex Launcher, make sure the "Startup boost" option in Edge is disabled.

**Comment by ams3401** [comment]
> The browser focusing problem is a known issue on Windows. I implemented a workaround for it, but it only runs for a specific list of process names. I just added `msedge_proxy.exe` to the list. Please try [this modified build](https://github.com/complexlogic/flex-launcher/files/9795111/flex-launcher-1.8-modified-win64.zip) and let me know if it works for you. If so, I'll merge the change for a new formal release.
> 
> As a side note: when using Edge with Flex Launcher, make sure the "Startup boost" option in Edge is disabled.

It works great! Thank you.
I discovered another issue while testing this, should I close this thread and open a new one?

**Comment by complexlogic** [comment]
> I discovered another issue while testing this, should I close this thread and open a new one?

Yes.

**Comment by complexlogic** [comment]
Actually, keep this one open until I merge the fix into `master`. Make a new issue for the other problem.
