### ISSUE TITLE
Feature request: OnLaunch=Close

### ISSUE THREAD

**Issue by brettinternet** [complexlogic/flex-launcher#26]
On multimonitor setups where the app may open in a separate window or just non-fullscreen setups, it would be nice to have the launcher close after launching an application. Would you consider this as an option?

**Comment by complexlogic** [comment]
This would be easy to implement, but I'm curious what the practical use case is. Do you have a multimonitor HTPC setup?

**Comment by DominoLeChat** [comment]
This would be a great feature ! I'm using this software on a Steam Deck running windows to choose between Steam BigPicture and normal Steam at boot.

**Comment by complexlogic** [comment]
@DominoLeChat Thanks for the context, I'll add this feature in the near future.

**Comment by brettinternet** [comment]
The steam deck is a great idea! I've also used a laptop in a similar way.

**Comment by complexlogic** [comment]
@brettinternet @DominoLeChat The new OnLaunch mode is called "Quit", and will cause the launcher to quit immediately after the successful launch of an application.

**Comment by brettinternet** [comment]
Thank you!
