### ISSUE TITLE
Feature request: Gentoo ebuild

### ISSUE THREAD

**Issue by CarDGee** [complexlogic/flex-launcher#29]
I am building a gentoo based htpc and this is just what I was looking for, simple and powerfull.
Could you add a gentoo ebuild to it?
Many thanks

**Comment by complexlogic** [comment]
I have no experience with Gentoo. Can you explain what ebuild is and what would be required to support it?

**Comment by CarDGee** [comment]
Thank you for the reply.
A ebuild is to gentoo what a PKGBUILD is to arch (maybe a bit more complex).... perhaps if you can post flex-launcher PKGBUILD I might be able to (with my limited skills) to write a ebuild from it and post it here.

**Comment by complexlogic** [comment]
The PKGBUILD is available [here](https://github.com/complexlogic/flex-launcher/blob/master/config/PKGBUILD.in). This is actually a configuration file for a PKGBUILD and CMake will fill in the appropriate variables at compile time (e.g. `@VARIABLE@`).

This should be able to get you started for how a build script for Flex Launcher needs to work.

**Comment by complexlogic** [comment]
I don't plan to support ebuilds within this repository. However, if another user has created an ebuild elsewhere, I may link to it in the installation section. Create a PR in that case.
