### ISSUE TITLE
Raspberry Pi Support - Initial Issues/Notes

### ISSUE THREAD

**Issue by ColonelPanicks** [complexlogic/flex-launcher#3]
Over the last few days I've been working on getting Flex Launcher running on the Raspberry Pi. Below are my findings.

## System Overview

Hardware: Raspberry Pi 4 (4GB)
OS: Raspbian Buster 
DM/DE: LightDM/LXDE

## Compilation

The version of CMake available is 1.16 so below the min required of 1.18. This is easily addressed by compiling CMake 1.22 from source:
```
get https://github.com/Kitware/CMake/releases/download/v3.22.1/cmake-3.22.1.tar.gz

tar xf cmake-3.22.1.tar.gz
cd cmake-3.22.1/

./bootstrap # Takes about 30 mins
make # Takes about 45 mins
sudo make install
```

After doing this, compilation completes as expected and Flex Launcher can be run.

## Window Display Issues

The main issue observed with using this is two-fold:
- The minimisation of the Flex Launcher on external command launch 
- The failure to restore the window post-closure of external command

### Minimisation of Flex Launcher

Perhaps more of an implementation consideration than a bug, the minimisation of Flex Launcher will display the desktop due to the minimisation. 

This can easily be worked around by commenting out [line 960](https://github.com/complexlogic/flex-launcher/blob/6d0013cd5b20349ff8725d0f091e09a3b8c0c504/src/launcher.c#L960) and recompiling. 

### Failure to Restore Window

This issue is a bit more confusing and, through some trial and error, I think I've managed to narrow down something _close_ to a fix and hopefully some information to make addressing this issue simpler. 

After closing an external command from Flex Launcher launched with Flex Launcher an odd thing happens - the window minimizes (this is true even with the minimisation prevention mentioned earlier). It can be restored by clicking the minimised window in the system tray and pressing the left or right arrow keys (to trigger a screen redraw). 

I started [debugging the window flags](https://stackoverflow.com/questions/46855423/sdl-getwindowflags-returns-seemingly-random-values) (see diff below) to identify what was going wrong and tested various combinations of `ShowWindow`, `RestoreWindow` and `MaximizeWindow` to try and restore the flags to the pre-launch state... Strangely, having all of these would get them close but the window would not reappear and would remain minimized. 

Further investigation showed that [some event polling](https://stackoverflow.com/questions/63406428/why-does-my-window-only-get-shown-after-i-use-sdl-pollevent) may be needed (I'm unfamiliar with C++/SDL/GUI Development so do not understand the reasons behind this right now).

Adding in polling seemed to get the window to restore the flags and get _closer_ to working as expected. Sometimes there is a flash of the desktop on external command closure before the launcher is restored. Other times it ends up in a similar state to having been restored-but-not-redrawn and an arrow press makes the launcher visible again.

I'm not quite sure how to address this but I hope it brings some clarity regarding my issues getting this to run on Raspberry Pi. 

## Troubleshooting Modifications

Below are the changes I made to get this close to working

```
diff --git a/src/launcher.c b/src/launcher.c
index 6d70fd8..50550aa 100755
--- a/src/launcher.c
+++ b/src/launcher.c
@@ -86,6 +86,7 @@ highlight_t *highlight = NULL; // Pointer containing highlight texture and coord
 bool updates; // Bool to update the screen at the end of the main loop
 geometry_t geo; // Struct containing screen geometry for the current page of buttons
 bool quit = false;
+void show_flags(int flags);
 
 // A function to initialize SDL
 int init_sdl()
@@ -893,6 +894,25 @@ void validate_settings()
   }
 }
 
+// Translate Window Flags
+void show_flags(int flags) {
+    printf("FLAGS ENABLED: ( %d )\n", flags);
+    if(flags & SDL_WINDOW_FULLSCREEN)         printf("SDL_WINDOW_FULLSCREEN\n");
+    if(flags & SDL_WINDOW_OPENGL)             printf("SDL_WINDOW_OPENGL\n");
+    if(flags & SDL_WINDOW_SHOWN)              printf("SDL_WINDOW_SHOWN\n");
+    if(flags & SDL_WINDOW_HIDDEN)             printf("SDL_WINDOW_HIDDEN\n");
+    if(flags & SDL_WINDOW_BORDERLESS)         printf("SDL_WINDOW_BORDERLESS\n");
+    if(flags & SDL_WINDOW_RESIZABLE)          printf("SDL_WINDOW_RESIZABLE\n");
+    if(flags & SDL_WINDOW_MINIMIZED)          printf("SDL_WINDOW_MINIMIZED\n");
+    if(flags & SDL_WINDOW_MAXIMIZED)          printf("SDL_WINDOW_MAXIMIZED\n");
+    if(flags & SDL_WINDOW_INPUT_GRABBED)      printf("SDL_WINDOW_INPUT_GRABBED\n");
+    if(flags & SDL_WINDOW_INPUT_FOCUS)        printf("SDL_WINDOW_INPUT_FOCUS\n");
+    if(flags & SDL_WINDOW_MOUSE_FOCUS)        printf("SDL_WINDOW_MOUSE_FOCUS\n");
+    if(flags & SDL_WINDOW_FULLSCREEN_DESKTOP) printf("SDL_WINDOW_FULLSCREEN_DESKTOP\n");
+    if(flags & SDL_WINDOW_FOREIGN)            printf("SDL_WINDOW_FOREIGN\n");
+    printf("\n");
+}
+
 // A function to execute the user's command
 void execute_command(char *command)
 {
@@ -957,14 +977,40 @@ void execute_command(char *command)
 
   // Launch external application
   else {
-    SDL_HideWindow(window);
+    //printf("Before hide flags\n");
+    //show_flags(SDL_GetWindowFlags(window));
+    //SDL_HideWindow(window);
+    printf("Before command flags\n");
+    show_flags(SDL_GetWindowFlags(window));
     #ifdef _WIN32
     cmd = convert_cmd(cmd);
     #endif
     system(cmd);
+    SDL_Event events;
+    SDL_PollEvent(&events);
+    //printf("After command flags\n");
+    //show_flags(SDL_GetWindowFlags(window));
+
     SDL_ShowWindow(window);
-    SDL_Delay(50);
+    SDL_PollEvent(&events);
+    printf("After show flags\n");
+    show_flags(SDL_GetWindowFlags(window));
+
+    SDL_MaximizeWindow(window);
+    SDL_PollEvent(&events);
+    printf("After maximize flags\n");
+    show_flags(SDL_GetWindowFlags(window));
+
+    SDL_RestoreWindow(window);
+    SDL_PollEvent(&events);
+    printf("After restore flags\n");
+    show_flags(SDL_GetWindowFlags(window));
+
     draw_screen();
+    SDL_PollEvent(&events);
+    printf("After draw flags\n");
+    show_flags(SDL_GetWindowFlags(window));
+
     updates = false;
```

**Comment by complexlogic** [comment]
Thanks for the report.

The 3.18 minimum CMake version was chosen specifically because it's the current version in the Debian stable repo. When developing the program, I decided to target the most recent Debian stable as the oldest configuration to support for Linux. You are running **Buster**, which is currently oldstable.

I wasn't able to reproduce your issue. I installed Raspbian **Bullseye** (stable) on my Pi 4 and updated all packages. I compiled Flex Launcher and used it to launch Kodi and Chromium (both installed from official repo), and I didn't have any issue at all. The launcher behaved exactly as it does on my x86 PC.

A quick check of the [Rasbian Buster package repo](https://archive.raspberrypi.org/debian/dists/buster/main/binary-armhf/Packages) shows that the version of SDL is 2.0.9, which is over 3 years old. 2.0.14 is the oldest version of SDL that I have tested the program on.

Please upgrade your Pi to Bullseye. With ```apt-cache show```, verify that libsdl2-dev has been upgraded to 2.0.14, then compile and test again.

**Comment by ColonelPanicks** [comment]
Ahhh my bad, I thought I'd upgraded to the latest available, my mistake. Will give this a go when I get a chance and report back. Cheers!

**Comment by ColonelPanicks** [comment]
Just tested on a fresh Bullseye install. All works as expected & the adjustment of commenting out line 960 & 965 gives me the desired behaviour of no minimising. Thank you!
