### ISSUE TITLE
Add feature to navigate from first icon to last icon and vice verse

### ISSUE THREAD

**Issue by WilliamLeGod** [complexlogic/flex-launcher#33]
Is it possible to navigate from first icon to last icon by pressing left and vice verse by pressing right?

For example: when I open Flex, it will auto hightlight the first icon/app, let's say I have total 4 of them, to navigate to the 4th icon, i have to press right 3 times, so is it possible to add a feature to just press left once, I can navigate to 4th icon from 1st icon?

Thanks!

**Comment by complexlogic** [comment]
No, but I will consider this feature for a future version.

**Comment by complexlogic** [comment]
@WilliamLeGod I've implemented this feature and it will be included in the next release.
