### ISSUE TITLE
Adding minimize argument to Command line

### ISSUE THREAD

**Issue by WilliamLeGod** [complexlogic/flex-launcher#34]
Document: "The path to the program executable that you want to launch"

I'm trying to launch a program minimized but I tried all kind of argument to no avail. 
Could you provide the worked argument for your launcher that minimize or hide the executable window?

(Example: C:\Game.exe - minimize -hide?)

Thanks!

**Comment by complexlogic** [comment]
Flex Launcher expects the launched application to be fullscreen by default. If you use the [:fork](https://github.com/complexlogic/flex-launcher/blob/master/docs/configuration.md#fork) special command, that will run any arbitrary command without exiting the launcher.

For example `:fork C:\Game.exe - minimize -hide`

**Comment by WilliamLeGod** [comment]
Thanks for the help!
