### ISSUE TITLE
Adding feature for only 1 instance of flex launcher.exe

### ISSUE THREAD

**Issue by WilliamLeGod** [complexlogic/flex-launcher#35]
Hi!

Is it possible to run only 1 instance of the launcher.exe? 
For example: if launcher is already opened, double click on the exe, it will refocus on the existing launcher instead of opening the 2nd launcher exe

Thanks!

**Comment by complexlogic** [comment]
This isn't directly supported in the program, but it's easy to implement using a batch script. See [this StackOverflow post](https://stackoverflow.com/questions/162291/how-to-check-if-a-process-is-running-via-a-batch-script) for example.
