### ISSUE TITLE
Starting flex-launcher on the rpi4 fails to initialize SDL

### ISSUE THREAD

**Issue by YetAnotherSimon** [complexlogic/flex-launcher#38]
Hi folks, 
I was hoping to get this tool running on my rpi4 (with raspberry pi os). Sadly, as soon as I try to start it, the following error message appears:
```bash
$ flex-launcher 
Could not initialize SDL
wayland,x11 not available
```
This happens no matter if I try to start it from a console in the desktop mode on in a console tty. Using the desktop file works neither. 

I hope someone can help. Thanks!

**Comment by complexlogic** [comment]
Try launching like this, from a console in desktop mode:
`SDL_VIDEODRIVER=x11 flex-launcher`

**Comment by Albusaidi30** [comment]
Could not initialize SDL
x11 not available

RP3B+ with lite os , could not laucnh
