### ISSUE TITLE
Not launching on raspberry pi OS 64 bit

### ISSUE THREAD

**Issue by philipm92** [complexlogic/flex-launcher#39]
I installed flex-launcher like written in the doc on my raspberry pi 4 8GB with raspberry Pi OS 64 bit.
But no matter what I do I cannot get it to launch.

I put the . desktop in
`/.config/autostart`

And when I try to launch it from the terminal I get:
```
Could not initialize SDL
wayland,x11 not available
```

The config file is in the recommended location.

Thanks for the help.

Kind regards
Philip

**Comment by complexlogic** [comment]
Try the workaround described in #38

**Comment by philipm92** [comment]
Great that worked. Thanks. 

How exactly can I get this to work on startup? Do I have to add something to the .desktop or launch a bash script at startup?
