### ISSUE TITLE
compiled v2.1 on Raspberry OS x32 bullseye (RPI-2): error on start

### ISSUE THREAD

**Issue by apuokas** [complexlogic/flex-launcher#40]
Hallo, thenk you for wery nice and usefull job. Im using flex-louncher on my HTPC amd64. But i trying to use it on RPI2 too. I could compile v2.1 on RPI2 without errors, but if i start on terminal, i becomme "flex-launcher" window with "a critical error occured. Check the log file for details" + button "ok" and in terminal i see "Could not initialize SDL / wayland,x11 not available". After i found a older v1.8 x32 deb file for RPI and installed. I can launch v1.8 from desktop menu and from terminal. I compilled v1.8 too and i can launch compilled v1.8. After tahet i try to compile v2.1 again, but i becomme same error. There is all that i have enabled in /boot/config.txt: dtparam=audio=on, camera_auto_detect=1, display_auto_detect=1, dtoverlay=vc4-fkms-v3d, max_framebuffers=2, disable_overscan=1, [cm4] otg_mode=1, [pi4] arm_boost=1. I tried compille v2.1 with dtoverlay=vc4-kms-v3d and with "#" disabled #dtoverlay=vc4-kms-v3d and #dtoverlay=vc4-fkms-v3d, but i have the same error if i run v2.1.
Second Question is: i wich to change clock month and weekday language. I think i could maybe manipilate some file to change days and months names befor i compile v1.8? Can you say me please what can i do
And one suggestion: if date on clock is enabled, could be useful that row with date design (font etc) could be manipilatet too. Best regards.

**Comment by complexlogic** [comment]
The launch failure on Raspberry Pi is a known issue. Follow the workaround in #38, and I'll have it fixed for the next release.

As for the language, you can change your locale using the `localectl` program. For example:
```
sudo localectl set-locale LANG=en_US.UTF-8
```
Then, you can check the translated strings with `locale -k LC_TIME`. That's what Flex Launcher will use for the clock.
