### ISSUE TITLE
RPM package for Fedora?

### ISSUE THREAD

**Issue by ItsRogueRen** [complexlogic/flex-launcher#41]
Curious if there will ever be a Fedora RPM package for this as it seems super useful, but I would have to set up distrobox to use it on a Fedora system which is a bunch of extra set up I would like to avoid (I plan to use this on 3 or 4 machines so setting up distrobox AND this on each one would take quite a while longer than otherwise needed). 

If there aren't any plans for this, I can just use distrobox anyway.

**Comment by complexlogic** [comment]
I may consider making a Fedora package for the next release. You can still use it on Fedora without Distrobox, though. Just build it from source. I have the instructions in the [compilation guide](https://github.com/complexlogic/flex-launcher/blob/master/docs/compilation.md).

**Comment by complexlogic** [comment]
I have decided I am not going to provide binaries for Fedora, but thanks for the suggestion.
