### ISSUE TITLE
Trouble getting this to run on Bullseye Lite 64bit.

### ISSUE THREAD

**Issue by RyuHayabusa77** [complexlogic/flex-launcher#42]
I wanted to install and use this to act as an app launcher on a lite install of bullseye on my Raspberry Pi 4b 8gb.

When I try to launch it, i get the:

`Could not initialize SDL
wayland,x11 not available`

So I tried the:

`SDL_VIDEODRIVER=x11 flex-launcher`

Which told me "x11 not available". I guess this is normal because that would be included on the desktop gui version of bullseye and not the lite version. And I did try this on a regular (non lite) bullseye install and it worked but I wanted to get it working on a lite install.

I searched around and thought I had found a possible way to install x11 by using this guide: https://dustinpfister.github.io/2020/03/27/linux-raspbian-lite-xserver-xorg/ but that didn't work.

I also tried just installing the top 3 packages from this site: https://raspberryconnect.com/raspbian-packages/67-raspbian-x11.

But its clear that I, being a linux/raspberry pi novice, have no idea what I'm doing.

How can I get X11 on a lite install of bullseye so I can make this work? Is it possible to just use a different video driver? Steamlink runs just fine with its GUI so whatever that is using must work for this launcher?

Please let me know, as I'd like to have a setup to launch just a few apps and I'd rather do it on the lite version to cut down on extra bloat, like a desktop environment that I don't need.

**Comment by complexlogic** [comment]
I recommend following the [Kiosk Mode Setup](https://github.com/complexlogic/flex-launcher/blob/master/docs/setup_linux.md#kiosk-mode-setup) instructions that I wrote. Raspberry Pi OS Lite is covered under that as an option. It installs a lightweight X11-based window manager, avoiding the bloat of a full desktop environment.

If you absolutely must not use X11 or Wayland, you should be able to run it directly on the hardware by using `SDL_VIDEODRIVER=kmsdrm`. The problem with that method is that the launcher isn't able to detect focus changes (which it uses to determine the state of the launched applications), so you'll need to use scripts to kill the launcher and start it again after the application returns. See #19 for more details.

**Comment by RyuHayabusa77** [comment]
Thanks very much for your quick reply, i really appreciate it. After going through those steps it seems to have done the job!
