### ISSUE TITLE
Set "command" as a keyboard key only

### ISSUE THREAD

**Issue by WilliamLeGod** [complexlogic/flex-launcher#57]
Hi!

Im trying to find how to add a keyboard key as a command: Entry=title;icon_path;command
Let's say F23: Entry=title;icon_path;F23 
But this doesn't work

Could you help me?

Thanks!

**Comment by complexlogic** [comment]
So, you want a command to execute when you press F23?

**Comment by WilliamLeGod** [comment]
> So, you want a command to execute when you press F23?

Thanks for getting back to me
A command that execute F23 (like pressing the button F23) only

**Comment by WilliamLeGod** [comment]
> > So, you want a command to execute when you press F23?
> 
> Thanks for getting back to me A command that execute F23 (like pressing the button F23) only

Like I set the icon, when I hit A on my controller to execute it, it executes the action of pressing F23 and then exit flex launcher

**Comment by WilliamLeGod** [comment]
u there bro?

**Comment by complexlogic** [comment]
Sorry for the late reply on this, but emulation of keystrokes is not possible to do with the launcher. Perhaps another program like AutoHotkey may be able to help you.
