### ISSUE TITLE
Blank screen causing issues on Windows 11

### ISSUE THREAD

**Issue by Starbuck1991** [complexlogic/flex-launcher#59]
I’ve been experimenting with flex-launcher on Windows 11, and the default blank screen that appears when launching an application is causing issues with various programs and emulators. These issues range from a black screen accompanied by background sounds to the inability to run an emulator and revert back to the frontend (this occurs with RetroBat). Generally, these issues are resolved when the application is simply run without blanking flex-launcher. This suggests that the problem may lie with the blanking technique used to conceal the launcher.

**Comment by complexlogic** [comment]
I just noticed the same thing on my Windows 10 machine running Steam. I'll investigate a solution.

**Comment by complexlogic** [comment]
I just changed the blanking code to something I believe is more correct. It's had to tell for sure because I think this issue may be hardware/driver dependent.

Please give [v2.2](https://github.com/complexlogic/flex-launcher/releases/tag/v2.2) a try, and if the issue still persists I can reopen.
