### ISSUE TITLE
 wayland,x11 not available

### ISSUE THREAD

**Issue by Albusaidi30** [complexlogic/flex-launcher#64]
I have RP3B+ and installed Raspberry Pi OS Lite (Debian 11 Bullseye) 64-bit with 16 GB SD card.
 I followed up with [Linux setup guide](https://complexlogic.github.io/flex-launcher/setup_linux#kiosk-mode-setup) with Kiosk mode. Everything is running smoothly, but I still get launch problems after boot. 

`
pi@pi:~$ flex-launcher
Could not initialize SDL
wayland,x11 not available
`

I have checked all the issues mentioned before and I followed the instructions, but still did not work.

**Comment by complexlogic** [comment]
Fixed by the new release [v2.2](https://github.com/complexlogic/flex-launcher/releases/tag/v2.2).
