### ISSUE TITLE
Black screen after launching Steam Link stream

### ISSUE THREAD

**Issue by ricprd** [complexlogic/flex-launcher#65]
I am trying Flex Launcher for my HTPC setup which includes Steam Link to stream from a PC.

However, for some reason, when I launch Steam Link and press the button to start streaming, I get a black screen. I have to Alt+Tab to the stream to see it, since it seems like Windows falls back to Flex Launcher and it sits at a black screen in this moment.

This does not happen if I launch Steam Link streaming from the desktop without Flex Launcher.

Am I doing something wrong or does Flex Launcher have an issue with streaming in Steam Link?

I'm using the latest versions of Flex Launcher and Steam Link in Windows 10.

**Comment by complexlogic** [comment]
Could you take a log? Run flex launcher from the terminal:

```
flex-launcher.exe -d
```

Then, reproduce the issue and upload the log. This may help me debug the issue.

**Comment by ricprd** [comment]
Awesome, I've attached the log in a text file: 
[flex-launcher-log.txt](https://github.com/user-attachments/files/17791660/flex-launcher-log.txt)

I reproduced the issue by doing the following:

1. Launched Flex Launcher via flex-launcher.exe -d
2. Launched the Steam Link in it (it points to a normal exe)
3. Steam Link shows its main screen, I press "Star playing"*
4. At this point, the screen goes blank and nothing happens (I also can't move the mouse, but I can hear the stream audio in the background)
5. If I Alt+Tab, I can see that this blank screen is actually Flex Launcher and it has stolen and kept the focus from the Steam Link stream**
6. I can Alt+Tab to the stream and then the Steam Link stream works
7. When I shutdown the Steam Link stream, I'm send back to the black screen
8. I can Alt+Tab back to the Steam Link initial screen and then close it from there, then I'm finally sent back to a visible Flex Launcher

It seems to me that the way Steam Link launches its stream is interfering with Flex Lancher. When I launch the Steam Link exe, it shows the main menu, and that works fine. But when I press "Start playing", it seems like this exe launches another window with the actual stream, which might be confusing Flex Launcher, which tries to take focus away from it but displays a black screen instead.

*Here is the main screen for reference:
![image](https://github.com/user-attachments/assets/57e08a71-113d-49f0-8da0-afa3ee7d1872)

**When the stream begins it displays the Steam library: 
![image](https://github.com/user-attachments/assets/48261256-8092-4fa1-b1ee-6688c5e0644e)

**Comment by complexlogic** [comment]
I just release [v2.2](https://github.com/complexlogic/flex-launcher/releases/tag/v2.2), which I believe should fix this issue. Can you give it a try? Wait at least 10 seconds to launch Steam Link after the launcher starts.

**Comment by ricprd** [comment]
> I just release [v2.2](https://github.com/complexlogic/flex-launcher/releases/tag/v2.2), which I believe should fix this issue. Can you give it a try? Wait at least 10 seconds to launch Steam Link after the launcher starts.

I can confirm version 2.2 fixes the issue after testing. Thank you for giving attention to this and congrats on the project :)
