### ISSUE TITLE
Implement that when you reach the last option, you return to the first one on the opposite side

### ISSUE THREAD

**Issue by Regradert** [complexlogic/flex-launcher#69]
It would be very handy to implement this, as it is inconvenient to have to go back through several icons to get to the icon at the other end.

Could this be implemented and enabled or disabled in the ini as desired?

Thank you and congratulations on this wonderful application.

**Comment by complexlogic** [comment]
This has already been implemented in the most recent release, v2.2. The setting is called `WrapEntries`. You can find it in your `config.ini` file.
