### ISSUE TITLE
The `:sleep` command not working on win10

### ISSUE THREAD

**Issue by BenzLeung** [complexlogic/flex-launcher#8]
I just leave the default `config.ini`, no changed.

I select `System` -> `Sleep`, but the launcher did not respond to this command.

My system is Win10 (Professional Version 21H2).

Could you tell me why?

(I am a Chinese. So Sorry for my bad English...)

**Comment by complexlogic** [comment]
Do ```:shutdown``` and ```:restart``` also fail, or is it only ```:sleep```? 

It would be helpful if you could take a debug log. Open a command prompt in the folder with Flex Launcher, then run:
```
.\flex-launcher.exe -d
```
Then try to select the sleep button and quit the program. This will create ```flex-launcher.log```. Please upload the log, it may have some messages that explain why it is failing.

**Comment by BenzLeung** [comment]
I have found the solution. The issue has nothing to do with Flex Lanucher.

1. Launch `regedit` with Win+R.
2. Navigate to path: `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SessionManager\Power`.
3. Set a DWORD name `AwayModeEnabled` and set its value to `0`.
4. Restart the Win10.
